### ISSUE TITLE
StableNormal + 2DGS

### ISSUE THREAD

**Issue by zhirui-gao** [Stable-X/StableNormal#26] opened 2024-11-02 08:29 UTC
Hi, thanks for your great work!
Do you release the baseline method that uses stable normal to enhance the 2DGS?

**Comment by lingtengqiu** [comment] 2024-11-02 14:15
Please keep patient! We are testing our model capacity, aiming at releasing more stable, accurate reconstruction pipeline.

**Comment by hugoycj** [comment] 2024-11-03 01:17
@zhirui-gao This appears to be a duplicate of [#15](https://github.com/Stable-X/StableNormal/issues/15). Please refer to that issue for updates on the code of baseline methods using StableNormal with 2DGS. I'll close this issue to keep discussions consolidated. Please feel free to follow and participate in #15 for updates.

**Closed by hugoycj** 2024-11-03 01:17 UTC
