### ISSUE TITLE
How to donwload weights?

### ISSUE THREAD

**Issue by CanCanZeng** [Stable-X/StableNormal#14] opened 2024-09-12 04:00 UTC
Hello, I have successfully run the algorithm from the command line. But I found that every time I run it, I have to access huggingface, which makes it slow to start at beginning. How do I follow the instructions in README to download the weights file locally?

**Comment by hugoycj** [comment] 2024-09-12 05:07
To download the necessary model weights, use the following commands:
```
huggingface-cli download --repo-type model --local-dir ./weights/stable-normal-v0-1 Stable-X/stable-normal-v0-1
huggingface-cli download --repo-type model --local-dir ./weights/yoso-normal-v0-3 Stable-X/yoso-normal-v0-3
```
Then you could use 
```
predictor = torch.hub.load("Stable-X/StableNormal", "StableNormal", trust_repo=True, local_cache_dir='./weights')
```
to load the weights from local

**Comment by CanCanZeng** [comment] 2024-09-12 05:58
Hello, I followed the command above to download the weights locally, but each time I run it, I still need to access huggingface. If I don't use a proxy, I won't be able to run it. Is there a way to run it completely locally?
Additionally, I would like to obtain the output of the network in order to obtain all possible results and save them in a custom format. What should I do?

**Comment by hugoycj** [comment] 2024-09-12 07:36
We will check the torch.hub.load("Stable-X/StableNormal", "StableNormal", trust_repo=True, local_cache_dir='./weights') with right local_cache_dir, it could run offline on our side. BTW, you could run following command to check whether the local mode work
```
python hubconf.py --input ./files/image/021-engine.jpg --output ./out.jpg
```

**Comment by hugoycj** [comment] 2024-09-12 07:37
As for the "all possible results", do you mean the intermediate x0 output from multi-step diffusion?

**Comment by CanCanZeng** [comment] 2024-09-12 09:07
I made a mistake, it's true that even if the internet is disconnected, it can still run normally. But what's strange is that sometimes it starts quickly, sometimes it freezes for a while during startup, and sometimes it gives an error. (But now I cannot reproduce the error situation)

All possible outputs refer to both my desire to obtain float type outputs and my desire to see if I can obtain outputs similar to confidence map. I can get float type outputs using hubconf.py now, but does not see anything like confidence map.

**Comment by hugoycj** [comment] 2024-09-13 16:44
We don't have a built-in confidence map in our pipeline unlike Marigold, since we don't use ensemble approach by running multiple forward passes to calculate mean and variance as confidence. A similar confidence calculation method can be achieved by storing all the intermediate predicted x0 values from the denoising process. 

A more practical solution is to train an uncertainty estimation network like this, which can generate a more reliable confidence map. Also a good confidence map can be calculate by  inverse warping, like what Neuris done
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/851a9735-2086-421b-9182-deae6278919f">

**Comment by hugoycj** [comment] 2024-09-14 05:36
@CanCanZeng Thank you for your patience. I'm closing this issue as the download weight problem appears to be resolved. We're currently setting up a mirror in China for users who can't access Hugging Face. If you have any further questions about confidence levels or StableNormal output, please don't hesitate to open a new issue. We appreciate your feedback and involvement in improving our project.

**Closed** 2024-09-14 05:36 UTC
Labels: good first issue

**Comment by CanCanZeng** [comment] 2024-10-11 07:30
A network error occurred again when starting to run. The cached weights are all present, I don't understand why this problem occurs @hugoycj 
![image](https://github.com/user-attachments/assets/4867032b-f540-42fd-8d24-ebb74a0aeeaa)

**Comment by hugoycj** [comment] 2024-10-11 07:37
Seems another network issue caused by dinov2 loading. Do you have any suggestion @lingtengqiu

**Comment by WXizhi** [comment] 2024-11-07 08:20
> A network error occurred again when starting to run. The cached weights are all present, I don't understand why this problem occurs @hugoycj ![image](https://private-user-images.githubusercontent.com/26817559/375663862-4867032b-f540-42fd-8d24-ebb74a0aeeaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njc4NzMsIm5iZiI6MTczMDk2NzU3MywicGF0aCI6Ii8yNjgxNzU1OS8zNzU2NjM4NjItNDg2NzAzMmItZjU0MC00MmZkLThkMjQtZWJiNzRhMGFlZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNzcwNjhlNmQzYTk0ZWYyMmY4MWIxMmNkYjg3MmUwODNmYWY1OGZlMmEwYWFiMGU1M2UyYmQ0MzM0MzZmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5b0REU_ATyLshdH-D-HyKa9Mcswy4GSQ3Ek02_F0IvQ)

There is a solution mentioned in https://github.com/facebookresearch/dinov2/issues/91
